# Arquivo: Abex-IV---Cidade-do-Idoso-/backend/src/main/resources/application.properties

spring.application.name=api-idosos

# ATUALIZAR PARA host.docker.internal se o Postgres estiver fora do Docker
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/cidade_idoso 
spring.datasource.username=postgres
spring.datasource.password=1qaz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

